In [1]:
# # use this function with the "ignore" argument to ignore all warnings
# import warnings
# warnings.filterwarnings('ignore')

# # If there is a specific type of warning that you want to ignore, you can specify this type in the filterwarnings function
# warnings.filterwarnings('ignore', category=UserWarning) # You would replace UserWarning with the specific warning class
#                                                         # you wish to ignore.

# # For the case of ignoring warnings from specific libraries, you can add the module parameter:
# warnings.filterwarnings('ignore', module='numpy')  # Ignore warnings from numpy


In [3]:
import pandas as pd
# Read the CSV file
path = 'C:/Users/mdaminulisla.prodhan/All_My_Miscellenous/QSAR_Modeling_python_gl/s10_binary_target_value/unique_smiles_max_zscore_rat_descriptors_non_zero_edited_binary2.csv'
target_binary = pd.read_csv(path)
df_tb = target_binary
#df_tb

In [4]:
# Check the index of the DataFrame
index = df_tb.index
#index

In [5]:
# access the first column by positional index (0-based)
# first_column = df_tb.iloc[:, 0]
# first_column

In [6]:
# Get the name of the first column
first_column_name = df_tb.columns[0]
first_column_name

'SMILES'

In [7]:
# Set the first column as the index
df_tb.set_index(df_tb.columns[0], inplace=True)

# Display the modified DataFrame with the updated index
#print(df_tb)

In [8]:
# Get the name of the first column
first_column_name = df_tb.columns[0]
first_column_name

'target'

In [9]:
df = df_tb
#df

In [10]:
# 'target' cplumn encoding

#OrdinalEncoder from sklearn.preprocessing doesn't accept a mapping argument. For ordinal encoding with a custom order,
#you can use the OrdinalEncoder class from the category_encoders package instead. Here's how you can do it:
#First, install the category_encoders package, if it's not already installed. You can do so by running:

#!pip install category_encoders

import pandas as pd
import category_encoders as ce

# Assume we load data from a CSV file named 'data.csv'
#df = pd.read_csv('data.csv')

# Define an ordinal mapping for your classes
ordinal_mapping = {'non_toxic': 0, 'mild_toxic': 1, 'toxic': 2, 'extremely_toxic': 3}

# Initialize encoder
encoder = ce.OrdinalEncoder(mapping=[{'col': 'target', 'mapping': ordinal_mapping}])

# Apply encoder to 'target' column
df['target'] = encoder.fit_transform(df['target'])

# Now 'target' column is ordinal encoded
print(df['target'])


SMILES
[H][C@]12Cc3ccc(Oc4cc(C[C@]5([H])N(C)CCc6cc(OC)c(OC)c(Oc7cc1c(CCN2C)cc7OC)c56)ccc4OC)cc3                 3
CC1(C)CC[C@@H](CN1)Nc2ncc(c(n2)-c3c[nH]c4c(c(ccc34)C#N)P(C)(C)=O)C(F)(F)F                                3
Nc1ncc(cc1-c2nnc(CC3CC3)o2)-c4cnn(c4)C5CCNCC5                                                            3
O=C(OCC(COC(=O)c1ccccc1)OC(=O)c2ccccc2)c3ccccc3                                                          3
CC(C)Cc1nn(C)c(C)c1NS(=O)(=O)c2c(Cl)cc(cc2Cl)-c3ccnc(c3)N4CCNCC4                                         3
                                                                                                        ..
[H][C@@]12CC[C@H](C(=O)Cn3ccnc3)[C@@]1(C)CC[C@@]4([H])[C@@]2([H])CC[C@@]5([H])C[C@@](O)(COC)CC[C@]45C    0
COc1cc([C@@H](C)C(=O)N2CC[C@@]3(C2)CCc4cc(c(C)nc4N3)-c5ncccn5)c(F)cn1                                    0
CC1(C)COc2ccc(F)cc2CN3[C@@H](COc4cn5ncc(C(=O)N1)c5nc34)C(F)F                                             0
[Cl-].Cc1cccc(C)c1NC(=O)C[N+]3

In [11]:
#df

In [13]:
#.................Model-RandomForestClassifier....................................................
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@................................................

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

# Assume 'features' is a list of column names of your features
# features = ['feat1', 'feat2', ..., 'featn']

X = df.drop(columns='target')
y = df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

# Now you can use the model to predict on your test set
y_pred = model.predict(X_test)

# You can assess the performance of your model
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

           0       0.41      0.97      0.58        35
           1       0.00      0.00      0.00        18
           2       0.00      0.00      0.00        17
           3       0.00      0.00      0.00        16

    accuracy                           0.40        86
   macro avg       0.10      0.24      0.15        86
weighted avg       0.17      0.40      0.24        86



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
#......................................................................................
# try techniques like oversampling the minority classes (for example, using SMOTE),
# undersampling the majority class, or using a different metric that is more suitable 
# for imbalanced datasets (for example, AUC-ROC, precision, recall, F1-score).

In [37]:
#@@@@@@.........................oversampling........................................@@@@@@@@@@@@@@@@@@@@@

# 1. Oversampling with SMOTE:
# First, you'll need to install the imbalanced-learn package if you haven't already done so. You can install it using pip:

# "!pip install imbalanced-learn"


In [14]:
# Now, let's apply SMOTE (Synthetic Minority Over-sampling Technique) to oversample the minority classes.

from imblearn.over_sampling import SMOTE
from collections import Counter


# X = df.drop(columns='target')
# y = df['target']

smote = SMOTE()

X_res, y_res = smote.fit_resample(X, y)

print('Resampled dataset shape %s' % Counter(y_res))

# In this code, X and y are your features and target column respectively. After resampling, you'll 
# have a balanced dataset, which means there will be an equal number of samples for each class.


Resampled dataset shape Counter({3: 213, 2: 213, 1: 213, 0: 213})


In [15]:
#  after you have balanced the classes with SMOTE, you can fit the model using the resampled data.

# use the stacked model 

import numpy as np
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from mlxtend.classifier import StackingCVClassifier

from sklearn.model_selection import train_test_split
# Split the data
X_train, X_test, y_train, y_test = train_test_split(X_res, y_res, test_size=0.2, random_state=42)

# Define base learners
base_learners = [   
    ('rf_1', RandomForestClassifier(random_state=42)),
    ('rf_2', RandomForestClassifier(random_state=44)),
    ('KNN_1', KNeighborsClassifier()),
    ('KNN_2', KNeighborsClassifier())
]

# Initialize StackingClassifier with the Meta-Learner
stacked_model = StackingCVClassifier(classifiers=[clf for _, clf in base_learners], 
                                     meta_classifier=RandomForestClassifier(random_state=42), 
                                     use_features_in_secondary=True, 
                                     random_state=42)

# Fit the model with the training data
stacked_model.fit(np.array(X_train), np.array(y_train))

# Make predictions with the test data
y_pred = stacked_model.predict(X_test)

# Compute and print the confusion matrix and classification report
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdim

[[24  3  8 10]
 [ 7 32  1  2]
 [ 4  2 34  2]
 [ 4  1  4 33]]
              precision    recall  f1-score   support

           0       0.62      0.53      0.57        45
           1       0.84      0.76      0.80        42
           2       0.72      0.81      0.76        42
           3       0.70      0.79      0.74        42

    accuracy                           0.72       171
   macro avg       0.72      0.72      0.72       171
weighted avg       0.72      0.72      0.72       171



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:443: UserWarning: X has feature names, but KNeighborsClassifier was fitted without feature names
  warnings.warn(
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to 

In [16]:
#@@@...........the explanation of the above results............................... 
# The confusion matrix and the classification report you've shared indicates that the performance of your stacking model
# has improved after oversampling with SMOTE. Let's dissect these results:

Confusion matrix:

The rows of the confusion matrix correspond to the actual classes (from 'non_toxic' to 'extremely_toxic' respectively),
and the columns correspond to the predicted classes.

Class 0 (non_toxic): Out of 45 true instances, the model correctly predicted 23, but also misclassified 22 
instances (5 as class 1, 10 as class 2, and 7 as class 3).

Class 1 (mild_toxic): Out of 42 true instances, the model correctly predicted 32 and misclassified 10 
instances (3 as class 0, 6 as class 2, and 1 as class 3).

Class 2 (toxic): Out of 42 true instances, the model correctly predicted 35, but also misclassified 7 
instances (5 as class 0 and 2 as class 1).

Class 3 (extremely_toxic): Out of 42 true instances, the model correctly predicted 32, but also misclassified 10
instances (5 as class 0, 3 as class 1, and 2 as class 2).

Classification report:

The precision for each class reflects the ability of the classifier not to label a negative sample as positive.
The higher this number is, the better.

The recall (or sensitivity) shows how many positive samples were correctly identified by the model.
The higher this number is, the better.

The f1-score is a harmonic mean of precision and recall, providing a balance between them.

The support is the number of occurrences of each class in the actual distribution.


Summary:

The model's accuracy is 71%, which indicates a decent model fit. However, the model seems to perform best for
class 3 (extremely_toxic) with the highest F1-score of 0.78.

There is room for improvement, especially for class 0 (non_toxic), where the F1-score is lowest (0.57).

You might want to experiment with different models for stacking, tune the hyperparameters of your base learners
and meta-learner, or try different techniques to handle class imbalance.

In addition, you could also consider focusing on improving specific metrics depending on your problem requirements.
For instance, if identifying toxic and extremely toxic comments is of the highest priority, you might want to focus on
improving recall for classes 2 and 3.


SyntaxError: invalid syntax (582304273.py, line 5)

In [ ]:
There are several approaches you can take to improve the F1-score for the 'non_toxic' class (class 0) 
in your multiclass classification problem:

Model Tuning: Tune the hyperparameters of your classifiers. Grid search or randomized search can help identify the optimal
hyperparameters for your model.

Change Base Models: You may want to consider changing your base models in the stacking ensemble.Try using more diverse
models as base learners to capture different patterns in the data.

    
Feature Engineering: You could work on creating more informative features, or removing irrelevant ones. Feature importance
can be assessed with techniques like permutation importance, SHAP, or feature importance property of models like RandomForest.


Data Preprocessing: Check if your data is cleaned properly - are there any outliers or incorrect values that could be
affecting the performance? Are there any additional preprocessing steps you could apply, like normalization or 
standardization?

Handling Class Imbalance: Even though you've used SMOTE to oversample the minority classes, the performance for the
'non_toxic' class (majority class before oversampling) might have decreased. You might want to adjust the oversampling
rates or try a combination of oversampling and undersampling.

Cost-Sensitive Learning: You could make use of cost-sensitive learning where you assign a higher cost to misclassifying
'non_toxic' instances. Many models have a class_weight parameter that you can adjust.

Evaluate Other Metrics: In multiclass classification, the overall accuracy, macro-averaged F1-score or weighted F1-score
are usually more meaningful than the F1-score of a single class. You should also keep these overall metrics in mind while
trying to optimize the model.

Multi-Model Ensemble: Instead of using a stacking ensemble, you can try a multi-model ensemble technique like bagging or
boosting. Different ensemble methods have different strengths and can improve the overall performance of your model.

Remember, the best way to find the right approach is to experiment with different techniques, and validate the performance
using a validation set or cross-validation to prevent overfitting on the test set.

In [38]:
# hyperparameter tuning for the ""Random Forest Classifier"".... ""Grid Search-type-1""""""".....@@###############

# Grid Search parameters : n_estimators, max_depth, min_samples_split, min_samples_leaf

# Firstly, we need to set up a parameter grid - a dictionary of parameters and their potential values. Then, we'll instantiate
# a GridSearchCV object with the model and the parameter grid. We'll use cross-validation to get the best set of parameters.
# Here's how you would do it:

from sklearn.model_selection import GridSearchCV

# Set up the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300, 400],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Initialize a Random Forest model
rf = RandomForestClassifier()

# Initialize the GridSearch object
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3, scoring='f1_macro')

# Fit the GridSearch object to the data
grid_search.fit(X_res, y_res)

# Get the optimal parameters
best_params = grid_search.best_params_

print(f"Best parameters: {best_params}")

# Please note that hyperparameter tuning can be computationally expensive and take a long time to run,
# especially if you have a large parameter grid and a large dataset. Make sure to adjust the parameters accordingly
# based on your available computational resources.

Best parameters: {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 400}


In [44]:
# Once you've found the best parameters, you can use them to train your Random Forest model:
# Train a new RandomForest model with the best parameters
rf_best = RandomForestClassifier(**best_params)
rf_best.fit(X_res, y_res)


RandomForestClassifier(n_estimators=400)

In [49]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier

# Initialize the Random Forest Classifier with the best parameters
rf_best = RandomForestClassifier(n_estimators=400, random_state=42)

# Fit the model to the resampled data
rf_best.fit(X_res, y_res)

# Use the model to make predictions on the test data
predictions = rf_best.predict(X_test)

# Print the confusion matrix, accuracy, and classification report 
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions))


[[45  0  0  0]
 [ 0 42  0  0]
 [ 0  0 42  0]
 [ 0  0  0 42]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       1.00      1.00      1.00        42
           2       1.00      1.00      1.00        42
           3       1.00      1.00      1.00        42

    accuracy                           1.00       171
   macro avg       1.00      1.00      1.00       171
weighted avg       1.00      1.00      1.00       171



In [50]:
# Cross-validation can provide a better measure of your model's performance.

from sklearn.model_selection import cross_val_score

# Initialize the Random Forest Classifier with the best parameters
rf_best = RandomForestClassifier(n_estimators=300, random_state=42)

# Perform 5-fold cross-validation
scores = cross_val_score(rf_best, X_res, y_res, cv=10)

# Print the accuracy for each fold
print("Cross-Validation Accuracy Scores:", scores)

# Print the mean accuracy
print("Mean Cross-Validation Accuracy:", scores.mean())


Cross-Validation Accuracy Scores: [0.6744186  0.72093023 0.69411765 0.74117647 0.83529412 0.85882353
 0.87058824 0.84705882 0.85882353 0.90588235]
Mean Cross-Validation Accuracy: 0.8007113543091655


In [53]:
# Stratified k-fold cross-validation:
# This method can be beneficial for imbalanced datasets 
# because it maintains the ratio of the classes in each fold.

from sklearn.model_selection import StratifiedKFold, cross_val_score

# Initialize the Random Forest Classifier with the best parameters
rf_best = RandomForestClassifier(n_estimators=300, random_state=42)

# Define the StratifiedKFold object
skf = StratifiedKFold(n_splits=10)

# Use cross_val_score for model evaluation
cross_val_scores = cross_val_score(rf_best, X_res, y_res, cv=skf)

# Print the cross-validation accuracy scores and the mean accuracy score
print("Cross-Validation Accuracy Scores:", cross_val_scores)
print("Mean Cross-Validation Accuracy:", cross_val_scores.mean())

# Stratified k-fold cross-validation keeps the ratio of the classes in each fold consistent with the ratio
# in the full dataset. This method can lead to more accurate evaluation results on imbalanced datasets, 
# because it ensures that each class has a representative amount of samples in each fold.


Cross-Validation Accuracy Scores: [0.6744186  0.72093023 0.69411765 0.74117647 0.83529412 0.85882353
 0.87058824 0.84705882 0.85882353 0.90588235]
Mean Cross-Validation Accuracy: 0.8007113543091655


The cross-validation results indicate that the model's performance is consistent across different subsets of your data, which is a good sign. However, there is some discrepancy between the perfect accuracy obtained previously and the cross-validation scores. It's crucial to keep in mind that a perfect accuracy score could be a result of overfitting on the training data or a result of testing on a very similar distribution of data as your training set.

Cross-validation provides a more robust estimate of the model's ability to generalize to unseen data since it trains and evaluates the model on different subsets of the training data. Thus, the average cross-validation accuracy of approximately 0.79 is a more reliable estimate of your model's expected performance.

You can further attempt to improve this by:

Further hyperparameter tuning: Try tuning other hyperparameters of the model, for example, max_depth, min_samples_split, etc. for the random forest classifier.

Feature Engineering: Creating new features or modifying existing ones can often help improve model performance.

Ensemble Methods: Combining predictions from multiple models can often yield better results than using a single model.

Exploring other algorithms: Different machine learning algorithms may perform better or worse depending on the specific dataset and problem. Experimenting with different models (SVM, gradient boosting, neural networks etc.) might lead to better results.

Stratified k-fold cross-validation: This method can be beneficial for imbalanced datasets because it maintains the ratio of the classes in each fold.

In [ ]:
# hyperparameter tuning for the ""Random Forest Classifier"".... ""Grid Search-type-2""""""".....@@###############
from sklearn.model_selection import GridSearchCV

# Define the parameter grid
param_grid = {
    'n_estimators': [100, 200, 300, 400],
    'max_features': ['auto', 'sqrt'],
    'max_depth': [10, 20, 30, 40, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False],
    'criterion': ['gini', 'entropy'],
    'min_weight_fraction_leaf': [0.0, 0.1, 0.2, 0.3],
    'max_leaf_nodes': [None, 10, 20, 30, 40],
    'min_impurity_decrease': [0.0, 0.1, 0.2],
    'class_weight': [None, 'balanced']
}

# Initialize the RandomForestClassifier
rf = RandomForestClassifier(random_state=42)

# Initialize the GridSearchCV
grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2)

# Fit grid_search to the data
grid_search.fit(X_res, y_res)

# Get the best parameters
best_params = grid_search.best_params_

# Print the best parameters
print(best_params)


Fitting 3 folds for each of 172800 candidates, totalling 518400 fits


In [ ]:
# Get the best parameters
best_params = grid_search.best_params_

# Initialize the RandomForestClassifier with the best parameters
rf_best = RandomForestClassifier(n_estimators=best_params['n_estimators'],
                                 max_features=best_params['max_features'],
                                 max_depth=best_params['max_depth'],
                                 min_samples_split=best_params['min_samples_split'],
                                 min_samples_leaf=best_params['min_samples_leaf'],
                                 bootstrap=best_params['bootstrap'],
                                 criterion=best_params['criterion'],
                                 min_weight_fraction_leaf=best_params['min_weight_fraction_leaf'],
                                 max_leaf_nodes=best_params['max_leaf_nodes'],
                                 min_impurity_decrease=best_params['min_impurity_decrease'],
                                 class_weight=best_params['class_weight'],
                                 random_state=42)

# Fit the model to the resampled data
rf_best.fit(X_res, y_res)

# Use the model to make predictions on the test data
predictions = rf_best.predict(X_test)

# Print the confusion matrix, accuracy, and classification report 
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions))


In [54]:
# hyperparameter tuning for the ""Random Forest Classifier"".... ""RandomizedSearchCV-type-1""""""".....@@##########

# RandomizedSearchCV parameters :n_estimators, max_features,max_depth, min_samples_split, min_samples_leaf, bootstrap

from sklearn.model_selection import RandomizedSearchCV

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]

# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

rf = RandomForestClassifier()

# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_res, y_res)

# Output the best parameters
print(rf_random.best_params_)


Fitting 3 folds for each of 100 candidates, totalling 300 fits
{'n_estimators': 1400, 'min_samples_split': 2, 'min_samples_leaf': 1, 'max_features': 'auto', 'max_depth': 40, 'bootstrap': False}


In [55]:
# Get the best parameters
best_params = rf_random.best_params_

# Initialize the RandomForestClassifier with the best parameters
rf_best = RandomForestClassifier(n_estimators=best_params['n_estimators'],
                                 max_features=best_params['max_features'],
                                 max_depth=best_params['max_depth'],
                                 min_samples_split=best_params['min_samples_split'],
                                 min_samples_leaf=best_params['min_samples_leaf'],
                                 bootstrap=best_params['bootstrap'],
                                 random_state=42)

# Fit the model to the resampled data
rf_best.fit(X_res, y_res)

# Use the model to make predictions on the test data
predictions = rf_best.predict(X_test)

# Print the confusion matrix, accuracy, and classification report 
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions))


[[45  0  0  0]
 [ 0 42  0  0]
 [ 0  0 42  0]
 [ 0  0  0 42]]
1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        45
           1       1.00      1.00      1.00        42
           2       1.00      1.00      1.00        42
           3       1.00      1.00      1.00        42

    accuracy                           1.00       171
   macro avg       1.00      1.00      1.00       171
weighted avg       1.00      1.00      1.00       171



In [57]:
# Stratified K-fold Cross Validation-codetype-1: 
from sklearn.model_selection import StratifiedKFold, cross_val_score

# Initialize the StratifiedKFold object
strat_k_fold = StratifiedKFold(n_splits=10)

# Perform cross-validation on the model
cv_scores = cross_val_score(rf_best, X_res, y_res, cv=strat_k_fold, scoring='accuracy')

print(f'Cross-Validation Accuracy Scores: {cv_scores}')
print(f'Mean Cross-Validation Accuracy: {cv_scores.mean()}')


Cross-Validation Accuracy Scores: [0.68604651 0.69767442 0.72941176 0.78823529 0.84705882 0.88235294
 0.92941176 0.90588235 0.88235294 0.91764706]
Mean Cross-Validation Accuracy: 0.8266073871409029


In [61]:
# Stratified K-fold Cross Validation-codetype-2:

from sklearn.model_selection import StratifiedKFold, cross_val_score

# Initialize the RandomForestClassifier with the best parameters
rf_best = RandomForestClassifier(n_estimators=best_params['n_estimators'],
                                 max_features=best_params['max_features'],
                                 max_depth=best_params['max_depth'],
                                 min_samples_split=best_params['min_samples_split'],
                                 min_samples_leaf=best_params['min_samples_leaf'],
                                 bootstrap=best_params['bootstrap'],
                                 random_state=42)

# Define the StratifiedKFold object
skf = StratifiedKFold(n_splits=10)

# Perform cross-validation on the model
cv_scores = cross_val_score(rf_best, X_res, y_res, cv=skf)

print(f'Cross-Validation Accuracy Scores: {cv_scores}')
print(f'Mean Cross-Validation Accuracy: {cv_scores.mean()}')


Cross-Validation Accuracy Scores: [0.68604651 0.69767442 0.72941176 0.78823529 0.84705882 0.88235294
 0.92941176 0.90588235 0.88235294 0.91764706]
Mean Cross-Validation Accuracy: 0.8266073871409029


In [62]:
# # hyperparameter tuning for the ""Random Forest Classifier"".... ""RandomizedSearchCV-type-1""""""".....@@##########
# RandomizedSearchCV parameters : criterion,min_weight_fraction_leaf, max_leaf_nodes,  


from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import make_scorer, accuracy_score
import numpy as np

# Define the hyperparameters
hyperparameters = {
    'criterion': ['gini', 'entropy'],
    'min_weight_fraction_leaf': np.linspace(0.0, 0.5, 5),
    'max_leaf_nodes': [None] + list(np.linspace(10, 50, 500).astype(int)),
    'min_impurity_decrease': np.linspace(0, 0.2, 4),
    'class_weight': [None, 'balanced'],
    'n_estimators': list(range(100, 301, 100)),
    'max_depth': list(range(3, 20)),
    'min_samples_split': list(range(2, 11)),
    'min_samples_leaf': list(range(1, 11)),
    'max_features': ['auto', 'sqrt', 'log2'],
    'bootstrap': [True, False]
}

# Define the scoring function
scorer = make_scorer(accuracy_score)

# Initialize a RandomizedSearchCV object
rf_random = RandomizedSearchCV(estimator=RandomForestClassifier(),
                               param_distributions=hyperparameters,
                               n_iter=100,
                               scoring=scorer,
                               cv=3,
                               verbose=1,
                               n_jobs=-1)

# Fit the RandomizedSearchCV object to the data
rf_random.fit(X_res, y_res)

# Get the best parameters
best_params = rf_random.best_params_

print(best_params)


Fitting 3 folds for each of 100 candidates, totalling 300 fits
{'n_estimators': 100, 'min_weight_fraction_leaf': 0.0, 'min_samples_split': 4, 'min_samples_leaf': 6, 'min_impurity_decrease': 0.0, 'max_leaf_nodes': 45, 'max_features': 'auto', 'max_depth': 11, 'criterion': 'entropy', 'class_weight': 'balanced', 'bootstrap': False}


In [63]:
# Get the best parameters
best_params = rf_random.best_params_

# Initialize the RandomForestClassifier with the best parameters
rf_best = RandomForestClassifier(n_estimators=best_params['n_estimators'],
                                 max_features=best_params['max_features'],
                                 max_depth=best_params['max_depth'],
                                 min_samples_split=best_params['min_samples_split'],
                                 min_samples_leaf=best_params['min_samples_leaf'],
                                 bootstrap=best_params['bootstrap'],
                                 criterion=best_params['criterion'],
                                 min_weight_fraction_leaf=best_params['min_weight_fraction_leaf'],
                                 max_leaf_nodes=best_params['max_leaf_nodes'],
                                 min_impurity_decrease=best_params['min_impurity_decrease'],
                                 class_weight=best_params['class_weight'],
                                 random_state=42)

# Fit the model to the resampled data
rf_best.fit(X_res, y_res)

# Use the model to make predictions on the test data
predictions = rf_best.predict(X_test)

# Print the confusion matrix, accuracy, and classification report 
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))
print(classification_report(y_test, predictions))

#  class_weight='balanced' will adjust weights inversely proportional to class frequencies in the input data.
# It could be helpful if your classes are imbalanced. If 'None', all classes are supposed to have weight one.
# You can also specify your own weights as a dictionary in the form {class_label: weight}. For example,
# if you want to double the weight of class 1, you could set class_weight={0: 1, 1: 2}.
# In this script, I've included 'None' and 'balanced' in the grid.


[[41  0  3  1]
 [ 0 42  0  0]
 [ 0  0 42  0]
 [ 2  1  0 39]]
0.9590643274853801
              precision    recall  f1-score   support

           0       0.95      0.91      0.93        45
           1       0.98      1.00      0.99        42
           2       0.93      1.00      0.97        42
           3       0.97      0.93      0.95        42

    accuracy                           0.96       171
   macro avg       0.96      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



In [64]:
# Stratified K-fold Cross Validation-codetype-1: 
from sklearn.model_selection import StratifiedKFold, cross_val_score

# Initialize the StratifiedKFold object
strat_k_fold = StratifiedKFold(n_splits=10)

# Perform cross-validation on the model
cv_scores = cross_val_score(rf_best, X_res, y_res, cv=strat_k_fold, scoring='accuracy')

print(f'Cross-Validation Accuracy Scores: {cv_scores}')
print(f'Mean Cross-Validation Accuracy: {cv_scores.mean()}')


Cross-Validation Accuracy Scores: [0.55813953 0.65116279 0.62352941 0.68235294 0.78823529 0.77647059
 0.81176471 0.77647059 0.8        0.78823529]
Mean Cross-Validation Accuracy: 0.7256361149110807


In [65]:
# Stratified K-fold Cross Validation-codetype-2:

from sklearn.model_selection import StratifiedKFold, cross_val_score

# Initialize the RandomForestClassifier with the best parameters
rf_best = RandomForestClassifier(n_estimators=best_params['n_estimators'],
                                 max_features=best_params['max_features'],
                                 max_depth=best_params['max_depth'],
                                 min_samples_split=best_params['min_samples_split'],
                                 min_samples_leaf=best_params['min_samples_leaf'],
                                 bootstrap=best_params['bootstrap'],
                                 random_state=42)

# Define the StratifiedKFold object
skf = StratifiedKFold(n_splits=10)

# Perform cross-validation on the model
cv_scores = cross_val_score(rf_best, X_res, y_res, cv=skf)

print(f'Cross-Validation Accuracy Scores: {cv_scores}')
print(f'Mean Cross-Validation Accuracy: {cv_scores.mean()}')


Cross-Validation Accuracy Scores: [0.56976744 0.65116279 0.67058824 0.63529412 0.83529412 0.82352941
 0.87058824 0.83529412 0.83529412 0.84705882]
Mean Cross-Validation Accuracy: 0.7573871409028727


These are perfect results, with an accuracy of 1.0 and all metrics in the classification report also being 1.0. However, please note that getting a perfect result on your test set may also indicate that your model might be overfitting the data.

Overfitting occurs when a model learns the detail and noise in the training data to the extent that it negatively impacts the performance of the model on new data. This means that the noise or random fluctuations in the training data is picked up and learned as concepts by the model. But these concepts do not apply to new data and negatively impact the model's ability to generalize.

While the above results seem impressive, you should ensure the model's ability to generalize by doing one of the following:

Cross-Validation: This involves splitting the training data into several parts and training the model on different combinations of these parts, then validating the model on the remaining part(s).

Train with more data: If possible, providing more data to the model can help it generalize better.

Simplify the model: If your model is complex, try to simplify it by selecting fewer features, using simpler models, or tuning hyperparameters to reduce complexity.

Use regularization techniques: Regularization methods like L1 or L2 regularization, dropout etc., can help prevent overfitting by adding a penalty for complexity in the model.

Remember, while a model that perfectly fits the data might seem like the goal, it's essential that the model also performs well on unseen data. You might want to explore the above options to ensure your model is robust and can generalize well.

In [ ]:
#@@@@@@@@@@@@@@@@@@........................................................................